name: "Path Testing Workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - 'backend/**'      # Only trigger when files in the backend directory change
      - 'frontend/**'     # Only trigger when files in the frontend directory change

permissions:
  id-token: write
  contents: read

jobs:
  Backend-Test:
    name: Backend Test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'backend/') # Job-level condition
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo Backend Working Directory
        run: |
          echo "Backend changes detected."
          echo "Working Directory: './backend'"

  Frontend-Test:
    name: Frontend Test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'frontend/') # Job-level condition
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo Frontend Working Directory
        run: |
          echo "Frontend changes detected."
          echo "Working Directory: './frontend'"
