name: "Test: SonarQube Web Workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - './backend/**'
      - './frontend/**'
  push:
    branches:
      - main
    paths:
      - './backend/**'
      - './frontend/**'
permissions:
  id-token: write
  contents: read

jobs:
  Test-Sonar-Scan:
    name: Test Workflow for SonarQube Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set environment and working directory
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Environment: ${{ github.head_ref }}"
          
          WORKING_DIR="${{ github.event.pull_request.head.ref == 'backend' && 'backend' || 'frontend' }}"
          echo "Working Directory: $WORKING_DIR"

      - name: Simulate Sonar Scan (Dummy)
        run: echo "This is where the SonarQube scan would happen with the given values."
