name: "Path Testing Workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - 'backend/**'
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug Changed Files
        id: debug
        run: |
          echo "Changed files in PR:"
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || true)
          echo "changed_files=${CHANGED_FILES}" >> $GITHUB_ENV

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: check-changed-files
    if: contains(env.changed_files, 'backend/')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Backend Tests
        run: |
          echo "Running backend tests in './backend'"

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: check-changed-files
    if: contains(env.changed_files, 'frontend/')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Frontend Tests
        run: |
          echo "Running frontend tests in './frontend'"
