name: "Path Testing Workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - 'backend/**'
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  Test-Paths:
    name: Test Paths for Backend and Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug Changed Files
        run: |
          echo "Changed files in PR:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Echo Backend Working Directory
        if: contains(git diff --name-only ${{ github.event.before }} ${{ github.sha }}, 'backend/')
        run: |
          echo "Backend changes detected."
          echo "Working Directory: './backend'"

      - name: Echo Frontend Working Directory
        if: contains(git diff --name-only ${{ github.event.before }} ${{ github.sha }}, 'frontend/')
        run: |
          echo "Frontend changes detected."
          echo "Working Directory: './frontend'"
